name: nuget publish

on: [push]

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION_NAME: 'Jkulds.Micro.Auth.Api'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0

      - name: Restore dependencies
        run: nuget restore ./$SOLUTION_NAME/$SOLUTION_NAME.sln

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0

      - name: Build
        run: dotnet build ./$SOLUTION_NAME/$SOLUTION_NAME.sln --configuration $BUILD_CONFIG